const cases={
exchange:{name:'agent-exchange',type:'RUST / SQLITE / MCP',problem:'Два агенти працюють над одним кодом, але не бачать сесій одне одного. Через це зміни можуть дублюватися або конфліктувати.',solution:'MCP-сервер зберігає повідомлення й замки на теми у SQLite. Людина бачить стан у NOW.md та локальному вікні тільки для читання.',decision:'Сервер змінює лише позначені блоки NOW.md. Рукописний текст поза ними зберігається.',top:[['Агент A','MCP-клієнт'],['Агент B','MCP-клієнт']],core:['exchange-mcp','пошта · замки · render'],bottom:[['SQLite','спільний стан'],['NOW.md','дошка для людини'],['Web UI','тільки читання']],transport:'stdio / JSON-RPC',output:'збереження та відображення',caption:'Спрощено за README: спільне сховище координує роботу агентів, а дошка та UI роблять її видимою людині.',links:[['Репозиторій','agent-exchange'],['Повна схема','agent-exchange/blob/main/docs/architecture.md']]},
downloader:{name:'Downloader',type:'RUST / C# / AVALONIA',problem:'Завантаження мають продовжуватися після обривів і закриття вікна. Різні протоколи потребують спільної черги й керування.',solution:'Окремий процес ядра керує чергою. Вікно, CLI та браузерне розширення звертаються до нього через локальний канал; протоколи підключаються через контракт Protocol.',decision:'Спочатку дані записуються й синхронізуються, потім зберігається стан. Це допомагає коректно відновити завантаження після збою.',top:[['Avalonia / CLI','інтерфейси'],['Розширення','через nmhost']],core:['Rust core-service','черга · планувальник · події'],bottom:[['HTTP','сегменти / resume'],['HLS / DASH','потоки й доріжки'],['yt-dlp','YouTube']],transport:'локальний IPC',output:'контракт Protocol',caption:'Спрощено за README. ffmpeg використовується окремим процесом для зведення доріжок і роботи з контейнерами.',links:[['Репозиторій','downloader'],['Повна схема','downloader/blob/master/docs/architecture.json']]},
antigravity:{name:'Antigravity UA',type:'JAVASCRIPT / C# / PYTHON',problem:'Український інтерфейс IDE має перекладати елементи керування, зберігаючи код, термінал, користувацький ввід та іконки.',solution:'Словник перекладів і DOM-інжектор формують пакет локалізації. Автономний інсталятор створює резервну копію та дає змогу відновити оригінал.',decision:'TreeWalker і MutationObserver обробляють інтерфейс. Ділянки коду та термінали виключені з автоперекладу.',top:[['Словник','uk_translations.json'],['DOM-інжектор','JavaScript']],core:['Пакет локалізації','app_uk.asar'],bottom:[['Інсталятор','C# / WinForms'],['Резервна копія','app.asar.bak'],['Український UI','Antigravity 2.0']],transport:'підготовка ASAR',output:'встановлення з відновленням',caption:'Схема узагальнює склад і процес доставки локалізації. Словник містить понад 1 670 ключів за даними README.',links:[['Репозиторій','antigravity-ua'],['Повна схема','antigravity-ua/blob/main/docs/architecture.json']]},
umod:{name:'UMOD · від налаштування до запуску',type:'RUST / PYTHON / SHELL',problem:'Підключення Codex потребує конфігурації, вибору моделі й чинного токена. Ручне повторення цих кроків ускладнює щоденну роботу.',solution:'Installer готує конфігурацію та скрипти. GUI запускає проксі й Codex CLI. Локальний проксі підставляє Entra-токен та оновлює його до завершення строку дії.',decision:'Проксі слухає лише loopback. Credential-файл видається окремо; його вміст GUI не показує.',top:[['Installer','конфігурація'],['Rust GUI','запуск Codex CLI']],core:['umod-token-proxy','127.0.0.1:8787'],bottom:[['Microsoft Entra','отримання токена'],['UMOD inference','запити Codex']],transport:'Codex CLI → локальний проксі',output:'автентифікація та запити',caption:'Узагальнена схема двох пов’язаних репозиторіїв. Проксі оновлює токен за 5 хвилин до завершення строку дії.',links:[['GUI на GitHub','umod-codex-gui'],['Installer на GitHub','umod-installer']]}
};
const panel=document.getElementById('case-panel');
const tabs=[...document.querySelectorAll('[role="tab"]')];
const node=([title,sub],core=false)=>`<div class="node${core?' node-core':''}">${title}<small>${sub}</small></div>`;
function selectProject(id,focus=false){const c=cases[id];if(!c)return;tabs.forEach(t=>{const active=t.dataset.project===id;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;if(active&&focus)t.focus()});panel.setAttribute('aria-labelledby','tab-'+id);panel.innerHTML=`<article class="case"><div class="case-text"><span class="case-label">${c.type}</span><h3>${c.name}</h3><h4>ЗАДАЧА</h4><p>${c.problem}</p><h4>РІШЕННЯ</h4><p>${c.solution}</p><h4>ТЕХНІЧНИЙ АКЦЕНТ</h4><p>${c.decision}</p><div class="case-links">${c.links.map(([label,path])=>`<a href="https://github.com/RiasJ1Dar/${path}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`).join('')}</div></div><figure class="diagram" style="margin:0" aria-label="Схема архітектури ${c.name}"><div class="diagram-head"><span>АРХІТЕКТУРА</span><span>СПРОЩЕНА СХЕМА</span></div><div class="flow"><div class="flow-top">${c.top.map(n=>node(n)).join('')}</div><div class="flow-arrow"><span aria-hidden="true">↓</span>${c.transport}</div>${node(c.core,true)}<div class="flow-arrow"><span aria-hidden="true">↓</span>${c.output}</div><div class="flow-bottom">${c.bottom.map(n=>node(n)).join('')}</div></div><figcaption class="diagram-caption">${c.caption}</figcaption></figure></article>`}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectProject(tab.dataset.project));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();selectProject(tabs[next].dataset.project,true)})});
document.querySelectorAll('[data-select]').forEach(link=>link.addEventListener('click',()=>selectProject(link.dataset.select)));
selectProject('exchange');
